apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: log-monitor-frontend-config
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
spec:
  ingressClassName: nginx
  tls:
  - secretName: mapper-web-tls
    hosts:
    - mapper.tarchunk.win
  rules:
  - host: mapper.tarchunk.win
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mapper-web
            port:
              number: 443
